report:
  discord:
    channel: 
    token: 

  discord_reporter:
    channel: 
    token: 

  acunetix:
    host: 
    port: 
    token: 

settings:
  nuclei:
    enable: true
    interval: 86400 # rescan all targets in the watch list every 12h
    options: -severity "medium,high,critical" -c 200 -rl 200
  # nuclei_fuzzing:
  #   enable: true
  #   interval: 86400 # rescan all targets in the watch list every 12h
  #   options: -c 300 -rl 200
  dirsearch:
    enable: true
    interval: 86400 # rescan all targets in the watch list every 12h
    options: -w ./wordlists/mylist.txt -e 'php,asp,aspx,jsp,html,js' -x '400,403,404,301,307' -q --format=simple
  subdominator:
    enable: true
    interval: 43200 # rescan all targets in the watch list every 12h
    options: -eu --validate
  scan:
    timeout: 0 # global timeout for ALL tools in SECONDS, 0 = unlimited

subfinder:
  cmd: ./thirdparty/subfinder/subfinder -d {target} -all -t {threads} -config {config} -o {output} -v
  health: ./thirdparty/subfinder/subfinder --version
  formats:
    config: config/thirdparty/subfinder.yaml
    threads: 300

dnsrecon:
  cmd: python3 thirdparty/dnsrecon/dnsrecon.py -d {target} -D {wordlist} -t brt --threads {threads} -c {output}
  health: python3 thirdparty/dnsrecon/dnsrecon.py -h
  formats:
    threads: 300
    wordlist: wordlists/all.txt

dnscan:
  cmd: python3 thirdparty/dnscan/dnscan.py -d {target} -w {wordlist} -o {output} -R 8.8.8.8
  health: python3 thirdparty/dnscan/dnscan.py -h
  formats:
    threads: 300
    wordlist: wordlists/subdomains-top1mil.txt

sublist3r:
  cmd: python3 thirdparty/sublist3r/sublist3r.py -d {target} -t {threads} -o {output} -v
  health: python3 thirdparty/sublist3r/sublist3r.py -h
  formats:
    threads: 300

amass:
  cmd: ./thirdparty/amass/amass enum -passive -d {target} -o {output} -aw {alterations} -w {wordlist}
  health: ./thirdparty/amass/amass --version
  formats:
    wordlist: wordlists/subdomains-top1mil.txt
    alterations: wordlists/alterations.txt

aiodnsbrute:
  cmd: cd thirdparty && python3 -m aiodnsbrute.cli {target} -w ../{wordlist} -f ../{output} -o csv -t {threads}
  health: cd thirdparty && python3 -m aiodnsbrute.cli --help
  formats:
    threads: 1024
    wordlist: wordlists/mix.txt

puredns:
  cmd: ./thirdparty/puredns/puredns bruteforce {wordlist} {target} -w {output} -r {resolvers} 
  health: ./thirdparty/puredns/puredns -v
  formats:
     wordlist: wordlists/subdomains-top1mil.txt
     resolvers: thirdparty/Fresh-Resolvers/resolvers.txt

# waymore:
#   cmd: python3 thirdparty/waymore/waymore.py -i {target} {options} | urless |anew {output}
#   health: python3 thirdparty/waymore/waymore.py --version
#   formats:
#      options: -mode U -p 2

# gau:
#   cmd: ./thirdparty/gau/gau --o {output} {options} {target} | urless |anew {output}
#   health: ./thirdparty/gau/gau --version
#   formats:
#      options: --subs --blacklist "css,ico,gif,jpeg,png,bmp,svg,avi,mpg,mpeg,mp3,m3u8,woff,woff2,ttf,eot,mp4,wav,mov,wmv,doc,xls,pdf,zip,tar,7z,rar,tgz,gz,exe,rtp,jpg"